server:
  port: 9090
spring:
  application:
    name: payment-endpoint
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: password
    url: jdbc:mysql://127.0.0.1:32771/testapp
    username: root
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  main:
    allow-bean-definition-overriding: true
